name: neurorl

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - pip:
      - stable-baselines3
      - gymnasium
      - opencv-python
      - networkx
      - plotly
      - statsmodels