"""
==========================================================
Manuscript Neural Figures
Experiment 2

Description
-----------
Builds publication-ready neural figures from outputs generated by:
python -m scripts.analysis.neural_analysis

Outputs
-------
experiments/version_2_0/results/neural_analysis/manuscript/
  - figure1_neural_summary.png/.pdf
  - figure2_neural_pca_3d.png/.pdf
  - figure3_neural_trajectories.png/.pdf
  - figure4_success_failure.png/.pdf
  - figure_manifest.csv

==========================================================
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ROOT = Path("experiments/version_2_0/results/neural_analysis")
OUT = ROOT / "manuscript"
OUT.mkdir(parents=True, exist_ok=True)

CONDITIONS = ["P0", "L1", "L2", "L3", "R1", "R2", "R3"]
PALETTE = dict(zip(CONDITIONS, sns.color_palette("tab10", len(CONDITIONS))))


def set_style():

    sns.set_theme(style="ticks", context="paper")

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "DejaVu Serif"],
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            "figure.dpi": 300,
            "savefig.dpi": 600,
        }
    )


def read_inputs():

    required = {
        "policy_scores": ROOT / "policy_pca_scores.csv",
        "value_scores": ROOT / "value_pca_scores.csv",
        "episode_index": ROOT / "episode_index.csv",
        "rsa_policy": ROOT / "rsa_policy.csv",
        "rsa_value": ROOT / "rsa_value.csv",
        "decode_policy": ROOT / "decoding_confusion_policy.csv",
        "decode_value": ROOT / "decoding_confusion_value.csv",
    }

    missing = [str(path) for path in required.values() if not path.exists()]

    if missing:
        joined = "\n".join(missing)
        raise FileNotFoundError(f"Missing expected neural analysis outputs:\n{joined}")

    return {
        "policy_scores": pd.read_csv(required["policy_scores"]),
        "value_scores": pd.read_csv(required["value_scores"]),
        "episode_index": pd.read_csv(required["episode_index"]),
        "rsa_policy": pd.read_csv(required["rsa_policy"], index_col=0),
        "rsa_value": pd.read_csv(required["rsa_value"], index_col=0),
        "decode_policy": pd.read_csv(required["decode_policy"], index_col=0),
        "decode_value": pd.read_csv(required["decode_value"], index_col=0),
    }


def _downsample(df, max_points=5000):

    if len(df) <= max_points:
        return df

    return df.sample(n=max_points, random_state=42)


def _panel_label(ax, label):

    if hasattr(ax, "text2D"):
        ax.text2D(
            -0.12,
            1.05,
            label,
            transform=ax.transAxes,
            fontsize=12,
            fontweight="bold",
            va="top",
        )
        return

    ax.text(
        -0.12,
        1.05,
        label,
        transform=ax.transAxes,
        fontsize=12,
        fontweight="bold",
        va="top",
    )


def _plot_pca_scatter(ax, df, title):

    sampled = _downsample(df, max_points=8000)

    sns.scatterplot(
        data=sampled,
        x="PC1",
        y="PC2",
        hue="condition",
        palette=PALETTE,
        alpha=0.18,
        s=8,
        linewidth=0,
        legend=False,
        ax=ax,
    )

    centroids = (
        df.groupby("condition", as_index=False)[["PC1", "PC2"]]
        .mean()
        .sort_values("condition")
    )

    for _, row in centroids.iterrows():
        ax.scatter(
            row["PC1"],
            row["PC2"],
            s=80,
            edgecolor="black",
            linewidth=0.7,
            color=PALETTE[row["condition"]],
            zorder=3,
        )
        ax.text(
            row["PC1"],
            row["PC2"],
            row["condition"],
            fontsize=7,
            ha="center",
            va="center",
            color="black",
        )

    ax.set_title(title)
    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")


def _plot_heatmap(ax, mat, title, cmap, vmin=None, vmax=None, fmt=".2f"):

    sns.heatmap(
        mat,
        annot=True,
        fmt=fmt,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
        cbar=False,
        square=True,
        linewidths=0.4,
        linecolor="white",
        ax=ax,
    )
    ax.set_title(title)
    ax.set_xlabel("")
    ax.set_ylabel("")


def _row_normalize(cm):

    cm = cm.copy().astype(float)
    row_sum = cm.sum(axis=1).replace(0, np.nan)
    return cm.div(row_sum, axis=0).fillna(0.0)


def figure1_neural_summary(data):

    fig, axes = plt.subplots(2, 3, figsize=(12.5, 8.0), constrained_layout=True)

    _plot_pca_scatter(
        axes[0, 0],
        data["policy_scores"],
        "Policy latent PCA (PC1-PC2)",
    )
    _panel_label(axes[0, 0], "A")

    _plot_pca_scatter(
        axes[0, 1],
        data["value_scores"],
        "Value latent PCA (PC1-PC2)",
    )
    _panel_label(axes[0, 1], "B")

    _plot_heatmap(
        axes[0, 2],
        data["rsa_policy"],
        "RSA (policy)",
        cmap="coolwarm",
        vmin=-1,
        vmax=1,
    )
    _panel_label(axes[0, 2], "C")

    _plot_heatmap(
        axes[1, 0],
        data["rsa_value"],
        "RSA (value)",
        cmap="coolwarm",
        vmin=-1,
        vmax=1,
    )
    _panel_label(axes[1, 0], "D")

    dec_policy_norm = _row_normalize(data["decode_policy"])
    _plot_heatmap(
        axes[1, 1],
        dec_policy_norm,
        "Decoding confusion (policy, row-normalized)",
        cmap="Blues",
        vmin=0,
        vmax=1,
    )
    _panel_label(axes[1, 1], "E")

    dec_value_norm = _row_normalize(data["decode_value"])
    _plot_heatmap(
        axes[1, 2],
        dec_value_norm,
        "Decoding confusion (value, row-normalized)",
        cmap="Blues",
        vmin=0,
        vmax=1,
    )
    _panel_label(axes[1, 2], "F")

    fig.suptitle("Neural population summary across perturbation conditions", fontsize=13, y=1.02)

    png = OUT / "figure1_neural_summary.png"
    pdf = OUT / "figure1_neural_summary.pdf"

    fig.savefig(png, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)

    return [png, pdf]


def _plot_3d(ax, df, title):

    sampled = _downsample(df, max_points=10000)

    for condition in CONDITIONS:
        cdf = sampled[sampled["condition"] == condition]
        if cdf.empty:
            continue
        ax.scatter(
            cdf["PC1"],
            cdf["PC2"],
            cdf["PC3"],
            s=3,
            alpha=0.25,
            color=PALETTE[condition],
            label=condition,
        )

    ax.set_title(title)
    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.set_zlabel("PC3")


def figure2_pca_3d(data):

    fig = plt.figure(figsize=(12.5, 5.5), constrained_layout=True)

    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    _plot_3d(ax1, data["policy_scores"], "Policy latent 3D PCA")
    _panel_label(ax1, "A")

    ax2 = fig.add_subplot(1, 2, 2, projection="3d")
    _plot_3d(ax2, data["value_scores"], "Value latent 3D PCA")
    _panel_label(ax2, "B")

    handles, labels = ax2.get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=7, frameon=False)

    png = OUT / "figure2_neural_pca_3d.png"
    pdf = OUT / "figure2_neural_pca_3d.pdf"

    fig.savefig(png, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)

    return [png, pdf]


def _select_episodes(episode_df, per_condition=2):

    picks = []

    for condition in CONDITIONS:
        subset = episode_df[episode_df["condition"] == condition].copy()
        if subset.empty:
            continue

        success = subset[subset["success"] == True].head(per_condition)
        failure = subset[subset["success"] == False].head(1)

        chosen = pd.concat([success, failure], ignore_index=True)
        if len(chosen) > per_condition + 1:
            chosen = chosen.head(per_condition + 1)

        picks.append(chosen)

    if not picks:
        return pd.DataFrame(columns=episode_df.columns)

    return pd.concat(picks, ignore_index=True)


def _plot_trajectory_set(ax, score_df, selected_eps, title):

    for _, row in selected_eps.iterrows():
        start = int(row["start_index"])
        end = int(row["end_index"])

        traj = score_df.iloc[start:end]
        if traj.empty:
            continue

        condition = row["condition"]
        linestyle = "-" if bool(row["success"]) else "--"

        ax.plot(
            traj["PC1"].values,
            traj["PC2"].values,
            traj["PC3"].values,
            color=PALETTE[condition],
            alpha=0.85,
            linewidth=1.3,
            linestyle=linestyle,
        )

    ax.set_title(title)
    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.set_zlabel("PC3")


def figure3_trajectories(data):

    selected = _select_episodes(data["episode_index"], per_condition=2)

    fig = plt.figure(figsize=(12.5, 5.5), constrained_layout=True)

    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    _plot_trajectory_set(ax1, data["policy_scores"], selected, "Policy trajectories")
    _panel_label(ax1, "A")

    ax2 = fig.add_subplot(1, 2, 2, projection="3d")
    _plot_trajectory_set(ax2, data["value_scores"], selected, "Value trajectories")
    _panel_label(ax2, "B")

    legend_handles = []
    for condition in CONDITIONS:
        legend_handles.append(
            plt.Line2D([0], [0], color=PALETTE[condition], lw=2, label=condition)
        )
    legend_handles.extend(
        [
            plt.Line2D([0], [0], color="black", lw=1.5, linestyle="-", label="Success"),
            plt.Line2D([0], [0], color="black", lw=1.5, linestyle="--", label="Failure"),
        ]
    )

    fig.legend(handles=legend_handles, loc="upper center", ncol=9, frameon=False)

    png = OUT / "figure3_neural_trajectories.png"
    pdf = OUT / "figure3_neural_trajectories.pdf"

    fig.savefig(png, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)

    return [png, pdf]


def _pc_long(df):

    use = df[["success", "PC1", "PC2", "PC3"]].copy()
    out = use.melt(id_vars="success", var_name="PC", value_name="Score")
    out["Outcome"] = np.where(out["success"], "Success", "Failure")
    return out


def figure4_success_failure(data):

    policy_long = _pc_long(data["policy_scores"])
    value_long = _pc_long(data["value_scores"])

    fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.6), constrained_layout=True)

    sns.violinplot(
        data=policy_long,
        x="PC",
        y="Score",
        hue="Outcome",
        split=True,
        inner="quart",
        palette={"Success": "#2A9D8F", "Failure": "#E76F51"},
        ax=axes[0],
    )
    axes[0].set_title("Policy latent: success vs failure")
    axes[0].set_xlabel("")
    _panel_label(axes[0], "A")

    sns.violinplot(
        data=value_long,
        x="PC",
        y="Score",
        hue="Outcome",
        split=True,
        inner="quart",
        palette={"Success": "#2A9D8F", "Failure": "#E76F51"},
        ax=axes[1],
    )
    axes[1].set_title("Value latent: success vs failure")
    axes[1].set_xlabel("")
    _panel_label(axes[1], "B")

    axes[0].legend(frameon=False, title="")
    axes[1].legend_.remove()

    png = OUT / "figure4_success_failure.png"
    pdf = OUT / "figure4_success_failure.pdf"

    fig.savefig(png, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)

    return [png, pdf]


def save_manifest(paths):

    df = pd.DataFrame(
        {
            "file": [str(p) for p in paths],
            "exists": [p.exists() for p in paths],
        }
    )

    manifest = OUT / "figure_manifest.csv"
    df.to_csv(manifest, index=False)

    return manifest


def main():

    print("=" * 70)
    print("Generating manuscript-ready neural figures")
    print("=" * 70)

    set_style()
    data = read_inputs()

    outputs = []
    outputs += figure1_neural_summary(data)
    outputs += figure2_pca_3d(data)
    outputs += figure3_trajectories(data)
    outputs += figure4_success_failure(data)

    manifest = save_manifest(outputs)

    print()
    print("=" * 70)
    print("MANUSCRIPT FIGURES COMPLETE")
    print("=" * 70)
    for path in outputs:
        print(path)
    print(manifest)


if __name__ == "__main__":
    main()
