"""
==========================================================
Build Manuscript Composite Figure: Attractor Analysis

Authors:
Peter Ohue
Gunnar Blohm

Description
-----------
Combines the three attractor figures generated by
scripts/attractor_analysis.py into a single manuscript-ready
composite figure (panels A, B, C), matching the layout and
resolution convention used for the other manuscript figures
(paper/fig1_schematic.png ... fig6_learning.png).

Usage
-----
python scripts/build_manuscript_attractor_figure.py
==========================================================
"""

from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

SOURCE = Path("experiments/version_1_0/results/neural_analysis/attractor")
OUTPUT_PNG = Path("paper/fig7_attractor.png")
OUTPUT_SVG = Path("paper/figures/fig7_attractor.svg")

fig = plt.figure(figsize=(10, 9.5))

grid = fig.add_gridspec(2, 2, height_ratios=[1.0, 1.15], hspace=0.18, wspace=0.08)

ax_a = fig.add_subplot(grid[0, :])
ax_b = fig.add_subplot(grid[1, 0])
ax_c = fig.add_subplot(grid[1, 1])

panels = (
    (ax_a, "fig_attractor_phase_portrait.png", "A"),
    (ax_b, "fig_attractor_path.png", "B"),
    (ax_c, "fig_attractor_latent.png", "C"),
)

for ax, filename, label in panels:

    image = mpimg.imread(SOURCE / filename)

    ax.imshow(image)
    ax.axis("off")

    ax.text(
        0.0, 1.02, label,
        transform=ax.transAxes,
        fontsize=16,
        fontweight="bold",
        va="bottom",
        ha="left",
    )

fig.savefig(OUTPUT_PNG, dpi=300, bbox_inches="tight", facecolor="white")

OUTPUT_SVG.parent.mkdir(parents=True, exist_ok=True)
fig.savefig(OUTPUT_SVG, bbox_inches="tight", facecolor="white")

plt.close(fig)

print(f"Composite figure saved to:\n{OUTPUT_PNG.resolve()}\n{OUTPUT_SVG.resolve()}")
