"""
==========================================================
Build Manuscript Composite Figure: Attractor Analysis

Authors:
Peter Ohue
Gunnar Blohm

Description
-----------
Combines the three attractor figures generated by
scripts/attractor_analysis.py into a single manuscript-ready
composite figure (panels I, II, III), matching the layout and
resolution convention used for the other manuscript figures
(paper/fig1_schematic.png ... fig6_learning.png).

Fonts are set to Arial 10pt throughout (COSYNE convention);
panel labels use Roman numerals rather than letters. Panel
sizes are computed from each source image's pixel aspect
ratio (not a fixed grid ratio), so there is no dead space
between rows.

Usage
-----
python scripts/build_manuscript_attractor_figure.py
==========================================================
"""

from pathlib import Path

import matplotlib
matplotlib.rcParams["font.family"] = "sans-serif"
matplotlib.rcParams["font.sans-serif"] = ["Arial", "Helvetica", "DejaVu Sans"]
matplotlib.rcParams["font.size"] = 10

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

SOURCE = Path("experiments/version_1_0/results/neural_analysis/attractor")
OUTPUT_PNG = Path("paper/fig7_attractor.png")
OUTPUT_SVG = Path("paper/figures/fig7_attractor.svg")

TOTAL_WIDTH = 10.0       # inches
COLUMN_GAP = 0.2         # inches, between panel II and panel III
ROW_GAP = 0.35           # inches, between the top row and the bottom row
LABEL_STRIP = 0.3        # inches reserved above each row for the label
MARGIN = 0.1             # inches, outer margin on all sides

images = {
    "I": mpimg.imread(SOURCE / "fig_attractor_phase_portrait.png"),
    "II": mpimg.imread(SOURCE / "fig_attractor_path.png"),
    "III": mpimg.imread(SOURCE / "fig_attractor_latent.png"),
}
aspect = {key: img.shape[0] / img.shape[1] for key, img in images.items()}

row0_width = TOTAL_WIDTH - 2 * MARGIN
row0_height = row0_width * aspect["I"]

usable_width = TOTAL_WIDTH - 2 * MARGIN - COLUMN_GAP
row1_height = usable_width / (1 / aspect["II"] + 1 / aspect["III"])
col_width_ii = row1_height / aspect["II"]
col_width_iii = row1_height / aspect["III"]

fig_width = TOTAL_WIDTH
fig_height = (
    MARGIN + LABEL_STRIP + row0_height + ROW_GAP
    + LABEL_STRIP + row1_height + MARGIN
)

fig = plt.figure(figsize=(fig_width, fig_height))


def add_panel(x0, y0_from_top, width, height, image, label):
    rect = [
        x0 / fig_width,
        1 - (y0_from_top + height) / fig_height,
        width / fig_width,
        height / fig_height,
    ]
    ax = fig.add_axes(rect)
    ax.imshow(image)
    ax.axis("off")
    ax.text(
        0.0, 1.02, label,
        transform=ax.transAxes,
        fontsize=14,
        fontweight="bold",
        va="bottom",
        ha="left",
    )


top_y = MARGIN + LABEL_STRIP
add_panel(MARGIN, top_y, row0_width, row0_height, images["I"], "I")

bottom_y = top_y + row0_height + ROW_GAP + LABEL_STRIP
add_panel(MARGIN, bottom_y, col_width_ii, row1_height, images["II"], "II")
add_panel(MARGIN + col_width_ii + COLUMN_GAP, bottom_y, col_width_iii, row1_height, images["III"], "III")

fig.savefig(OUTPUT_PNG, dpi=300, facecolor="white")

OUTPUT_SVG.parent.mkdir(parents=True, exist_ok=True)
fig.savefig(OUTPUT_SVG, facecolor="white")

plt.close(fig)

print(f"Composite figure saved to:\n{OUTPUT_PNG.resolve()}\n{OUTPUT_SVG.resolve()}")
